Desenvolva um banco de dados e relacione tabelas através de chaves estrangeiras ou nomes de colunas iguais. Siga as instruções:
crie uma base de dados; 
crie tabelas nessa base de dados;
em cada tabela, adicione atributos;
insira dados em cada tabela;
utilize os comandos Joins para realizar consultas nas tabelas.

In [ ]:
-- Criar a base de dados
CREATE DATABASE IF NOT EXISTS biblioteca;
USE biblioteca;

-- Criar a tabela de autores
CREATE TABLE autor (
  id INT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL
);

-- Inserir alguns autores
INSERT INTO autor (id, nome) VALUES
  (1, 'Machado de Assis'),
  (2, 'Clarice Lispector'),
  (3, 'Carlos Drummond de Andrade');

-- Criar a tabela de livros
CREATE TABLE livro (
  id INT PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  autor_id INT,
  FOREIGN KEY (autor_id) REFERENCES autor(id)
);

-- Inserir alguns livros
INSERT INTO livro (id, titulo, autor_id) VALUES
  (101, 'Dom Casmurro', 1),
  (102, 'A Hora da Estrela', 2),
  (103, 'Sentimento do Mundo', 3);

-- Criar a tabela de empréstimos
CREATE TABLE emprestimo (
  id INT PRIMARY KEY,
  livro_id INT,
  data_emprestimo DATE,
  FOREIGN KEY (livro_id) REFERENCES livro(id)
);

-- Inserir alguns empréstimos
INSERT INTO emprestimo (id, livro_id, data_emprestimo) VALUES
  (201, 101, '2023-01-10'),
  (202, 102, '2023-02-15'),
  (203, 103, '2023-03-20');

-- Realizar uma consulta usando INNER JOIN para obter informações sobre empréstimos, livros e autores
SELECT
  emprestimo.id AS emprestimo_id,
  livro.titulo AS livro_titulo,
  autor.nome AS autor_nome,
  emprestimo.data_emprestimo
FROM emprestimo
INNER JOIN livro ON emprestimo.livro_id = livro.id
INNER JOIN autor ON livro.autor_id = autor.id;